### ISSUE TITLE
Update for switch.surveillance_station_home_mode fails

### ISSUE THREAD

**Issue by runevad** [RaysceneNS/SurveillanceStationHomeModeSwitch#1]
I can't seem to get this to work... could this be a user issue? I am using a user that has privileges to administrator group and privilege to user Surveillance Station. 

Do I need to create a new separate user inside Surveillance Station as well? 
Great work BTW, this is much more useful than my previous setup if we can get this to work. 

`2020-01-06 12:32:16 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.surveillance_station_home_mode fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/synologysurveillance/switch.py", line 111, in update
    enabled = self._surveillance.get_home_mode_status()
AttributeError: 'SurveillanceStation' object has no attribute 'get_home_mode_status'`

**Comment by RaysceneNS** [comment]
At first glance I'd say that this is a problem with library versioning rather than a user account problem within Synology. 

In my setup, I have a user account in Synology DSM that has permission to access Surveillance station, likely just as you've decribed above. 

Your stack trace (thank you!) shows this at the end:
`.. 'SurveillanceStation' object has no attribute 'get_home_mode_status' `
I believe that this is due to linking to the api py-synology version 0.2.0, where it should be py-synology version 0.3.0. The function get_home_mode_status() was added in 0.3.0 release of py-synology.

I'll have to dig in further to determine why the 0.3.0 library wasn't loaded when it is specified in my manifest.json

**Comment by runevad** [comment]
You are right, the issue is the py-synology 0.2.0. In my case it's the Synology Camera integration in Home Assistant that is using the py-synology 0.2.0. 
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/synology/manifest.json

When I removed the camera integration your code works fine!

Can we bump the Synology Camera integration to 0.3.0?

**Comment by RaysceneNS** [comment]
Nice work finding that,

I have the synology camera setup in my configuration as well.
This makes me wonder if the libraries are using a last in wins method? In my configuration.yaml the switch is configured after the camera, so thinking that may cause the library loaded by the camera to be replaced with 0.3.0 when the switch is configured later, just shooting in the dark here as I don't have HA in front of me at the moment to try moving the entries around.

Agree, that the best way to move forward is to get the Synology Camera Integration updated to use 0.3.0

**Comment by RaysceneNS** [comment]
Added methods to get and set home_mode_status() without dependencies. Commit is a955b141a4b5134156b8f3f7ef90aeb98eb45c78
